In [1]:
import numpy as np
import pandas as pd
import scipy

In [14]:
A = [0.1, 0.7, 0.2]
B = [0.35, 0.6, 0.05]

print(f"{np.sum(A)=}")
print(f"{np.sum(B)=}")
print()

C = np.outer(A, B)
print(C)


np.sum(A)=1.0
np.sum(B)=1.0

[[0.035 0.06  0.005]
 [0.245 0.42  0.035]
 [0.07  0.12  0.01 ]]


In [17]:
0.1 * 0.6

0.06

In [12]:
scipy.stats.gmean([0.1, 0.35])

0.18708286933869708

In [15]:
np.sqrt(C)

array([[0.18708287, 0.24494897, 0.07071068],
       [0.49497475, 0.64807407, 0.18708287],
       [0.26457513, 0.34641016, 0.1       ]])